### ISSUE TITLE
U okay?

### ISSUE THREAD

**Issue by GrigoryEvko** [6DammK9/nai-anime-pure-negative-prompt#1]
Dude are you okay? Need any help? Why would you do most of the stuff?

**Comment by 6DammK9** [comment]
- I'm fine, thank you. 
- Maybe [develop some model merger, read some model merging paper, and make a merged model](https://discord.gg/97gf85Yk) with me? lol
- Because it is my hobby instead of career, meanwhile I'm unfortunately educated, so that I choose to pursue ~~postmodernism~~ art instead of "AI career"?

BTW this issue will be closed because it is not related to any major topic in this repo.
